version: '3.7'

services:
  freqtrade:
    build: .
    container_name: freqtrade_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./config.json:/freqtrade/config.json
      - ./user_data/strategies:/freqtrade/user_data/strategies:rw
    entrypoint: ["bash", "-c", "source /freqtrade/.env && freqtrade trade --config /freqtrade/config.json --strategy BuyLowSellHigh"]
