apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freqtrade-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/seu-usuario/bot_freqtrade_strategies.git
    targetRevision: HEAD
    path: infra/charts
  destination:
    server: https://kubernetes.default.svc
    namespace: freqtrade
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: "*"
      jsonPointers:
        - /spec/replicas
