name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
    paths:
      - 'user_data/**'
      - 'config.json'
      - '.github/workflows/backend.yml'
      - 'Dockerfile.backend'
      - 'run_bot.sh'
      - 'render.yaml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'user_data/**'
      - 'config.json'
      - '.github/workflows/backend.yml'
      - 'Dockerfile.backend'
      - 'run_bot.sh'
      - 'render.yaml'
  repository_dispatch:
    types: [trigger-backend-workflow]

jobs:
  build-and-push-backend-docker:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/freqtrade-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/freqtrade-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
  deploy-to-render:
    runs-on: ubuntu-latest
    needs: build-and-push-backend-docker
    if: github.event_name != 'pull_request'
    
    steps:
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.3
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
          github_token: ${{ secrets.GITHUB_TOKEN }}