name: Main Orchestrator Workflow

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - 'frontend/**'
      - 'user_data/**'
      - 'Dockerfile.frontend'
      - 'Dockerfile.backend'
      - '.github/workflows/frontend.yml'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - 'frontend/**'
      - 'user_data/**'
      - 'Dockerfile.frontend'
      - 'Dockerfile.backend'
      - '.github/workflows/frontend.yml'
      - '.github/workflows/backend.yml'

jobs:
  trigger-frontend-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Trigger Frontend Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-frontend-workflow
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
  
  trigger-backend-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Trigger Backend Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-backend-workflow
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

# Note: Frontend and Backend pipelines are now separated into their own workflow files:
# - Frontend pipeline: .github/workflows/frontend.yml
# - Backend pipeline: .github/workflows/backend.yml
#
# This main workflow serves as an orchestrator that can trigger both pipelines
# when necessary. Each pipeline can also be triggered independently based on 
# specific file changes relevant to that component.